#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi

nvidia-settings --config "$XDG_CONFIG_HOME/nvidia/settings" --load-config-only &
xrdb -load "$XDG_CONFIG_HOME/X11/xresources" &
numlockx on &
xsetroot -cursor_name left_ptr &

if ${RUNWM:-true}; then
    exec bspwm
fi
