#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          35
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#333333"
bspc config active_border_color		"#7aa3f7"
bspc config focused_border_color	"#d65d0e"
bspc config presel_feedback_color	"#ff9e64"
#bspc config urgent_border_color 	"#dd2727"

#Dual monitor
#find out names with arandr or xrandr
bspc monitor VGA-0 -d 1 2 3 4 5 6 7 
bspc monitor HDMI-A-1 -d 8 9 10 11 12 13 14

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Oblogout Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

#Scratchpads
bspc rule -a term state=floating center=true 
bspc rule -a mail state=floating center=true 
bspc rule -a ranger state=floating center=true 
bspc rule -a Bitwarden state=floating center=true 
bspc rule -a pulse state=floating center=true 
bspc rule -a mus state=floating center=true 

bspc rule -a scratchpad sticky=on state=floating hidden=on
# check scratchpad already running
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e /usr/local/bin/scratch &

# change cava colorscheme
CAVA_PATH="$HOME/.config/cava"
cp "$CAVA_PATH"/colorschemes/gruvbox "$CAVA_PATH"/config
