#!/bin/bash
# X settings
xsetroot -cursor_name left_ptr &

# Compositor
runonce picom --experimental-backends &

# Polkit agent
#runonce /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 
runonce /usr/lib/mate-polkit/polkit-mate-authentication-agent-1

# Bspswallow
#pgrep bspswallow || bspswallow &

# Lockscreen
xset s 600 1
xss-lock -n 'systemctl suspend' -- betterlockscreen -l dimblur &

# Autostart apps
runonce flameshot
runonce nm-applet
dex -a -s ~/.config/autostart &
#runonce clipmenud
clipmenud &
#runonce xfce4-power-manager --daemon
