#!/bin/bash
# Run only when not running already!
function run {
  if ! pidof -x $1 ;
  then
    $@&
  fi
}

function run2 {
  if ! pidof -x $1 ; then
	while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
	$@&
  fi
}

function check2 {
  if ! pidof -x $1 ; then
	  $@&
	  while ! pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
  fi
}

function check3 {
 $@&
  while ! pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
}

function run3 {
  if ! pidof -x $1 ; then
	killall -q $1&
        while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
        $@&
  fi
}

function reload {
  killall -9 $1 &
  while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
  $@&
}

function runonce {
  if ! pidof -x $1 ;
  then
    $@&
  fi 
}
