#!/bin/sh

#BSPWM configuration
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          35
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config initial_polarity first_child

#BSPWM coloring
bspc config normal_border_color		"#333333"
bspc config active_border_color		"#7aa3f7"
bspc config focused_border_color	"#d65d0e"
bspc config presel_feedback_color	"#ff9e64"
#bspc config urgent_border_color 	"#dd2727"

#Floating applications
bspc rule -a Lxappearance state=floating
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Nm-connection-editor state=floating

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor VGA-0 -d 1 2 3 4 5 6 7
#bspc monitor DP-2 -d 1 2 3 4 5 6 7
#bspc monitor LVDS1 -d 1 2 3 4 5 6 7
#bspc monitor DP3 -d 1 2 3 4 5 6 7
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7
#bspc monitor HDMI2 -d 1 2 3 4 5 6 7

#Autostart
$HOME/.config/bspwm/autostart.sh
