#!/bin/bash
# only source other files here
#------------------------------
THEME="gruvbox"

# Configuration
source $XDG_CONFIG_HOME/bspwm/themes/bspwm-$THEME

# Application rules
source $XDG_CONFIG_HOME/bspwm/bspwm-rules

# Monitors
source $XDG_CONFIG_HOME/bspwm/bspwm-monitors

# Autostart
#source $HOME/.config/bspwm/bspwm-functions
source $XDG_CONFIG_HOME/bspwm/autostart/$THEME.sh
source $XDG_CONFIG_HOME/bspwm/bspwm-autostart
source $XDG_CONFIG_HOME/bspwm/bspwm-postload
